### PR TITLE
Contribution to this patch

### PR DESCRIPTION
**Pull request by renyhp**
I rebased onto the newest master, added the requested docs and fixed some very little errors. You can merge if you wish, otherwise just drop this PR :)
BTW I feel that a better implementation would be to have only one argument, which can be a path, an url, or a file_id, just like Telegram does, but I don't know how to do that properly, plus I think @pietroalbini should have the final say about it.

### CODE REVIEW

**Comment by renyhp** [comment]
Sorry for this last double commit. I resolved the merge conflicts.

**Comment by pietroalbini** [comment]
I'll review this in the next few days, I'm not at home ATM.

**Comment by pietroalbini** [comment]
> BTW I feel that a better implementation would be to have only one argument, which can be a path, an url, or a file_id, just like Telegram does, but I don't know how to do that properly, plus I think @pietroalbini should have the final say about it.

I don't like that so much: botogram would have to detect what the argument contains (for example a `file_id` or a `path`) to avoid breaking compatibility, and it's not something you can do without hitting corner cases.

By the way, why you rebased on master? It shouldn't be needed...

**Comment by renyhp** [comment]
I rebased because I saw there were conflicts between his PR and botogram's master.

As for the implementation, another proposal I could advance to still have only one argument, is to have another argument which should be called something like "mode" and should only be either "file_id", "url" or "path". That way botogram can know how you're passing the file. Again, it's up to you.

**Pull request merged**
